---
version: "3.9"

services:
  my_dagster_project:
    image: zeldas_image
    profiles: 
      - dagster
    networks:
      - dagster_network
    ports: 
      - "3000:3000"
  postgresql:
    image: postgres:11
    container_name: postgresql
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
    profiles:
      - dagster
    networks:
      - dagster_network 

networks:
  dagster_network:
    driver: bridge
    name: dagster_network