name: 'zeldas_dbt_models'
version: '1.0.0'
config-version: 2

profile: 'snowplow-bq'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  zeldas_dbt_models:
    sources: 
      snowplow: 
        +materialized: ephemeral
    staging:
      snowplow: 
        +materialized: view